name: Update

on:
  schedule:
    - cron:  '0 0 * * 0'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download server lists and update list files
        run: |
          mkdir -p generic
          mkdir -p foxyproxy
          declare -a countrycode=("au" "ca" "fr" "de" "hk" "id" "jp" "nl" "sg" "se" "ch" "tw" "uk" "us")
          declare -a countryid=("13" "38" "74" "81" "97" "101" "108" "153" "195" "208" "209" "211" "227" "228")
          for (( i=0; i<${#countrycode[@]}; i++ ));
          do
            curl --silent "https://api.nordvpn.com/v1/servers/recommendations?filters\[country_id\]=${countryid[$i]}&filters\[servers_technologies\]\[identifier\]=proxy_ssl&limit=100" | jq --raw-output '.[].hostname' > generic/${countrycode[$i]}.txt
            cat generic/${countrycode[$i]}.txt | while read line; do echo "ssl://username:password@${line}:89" >> foxyproxy/${countrycode[$i]}.txt; done
          done

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          message: "Automatically updated IP lists using GitHub Actions"
